In [2]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
df = pd.read_csv("E:\\Coding\\Portfolio Projects\\Customer Journey Analysis, Intervention and Performance Tracking\\dropoff_project\\data\\user_journey_raw.csv")
df

,user_id,entry_date,segment,device,region,age_group,period,month,stage1_date,stage2_date,stage3_date,stage4_date,stage5_date,conversion_date,converted,exit_stage,reached_stage2,reached_stage3,reached_stage4,reached_stage5
0,U001000,2024-06-12,Paid_Search,Tablet,West,35-44,Post-Intervention,2024-06,2024-06-12,2024-06-12,2024-06-13,2024-06-15,NaN,NaN,0,Stage4,1,1,1,0
1,U001001,2024-03-11,Referral,Desktop,North,55+,Pre-Intervention,2024-03,2024-03-11,NaN,NaN,NaN,NaN,NaN,0,Stage1,0,0,0,0
2,U001002,2024-03-03,Organic,Mobile,North,25-34,Pre-Intervention,2024-03,2024-03-03,2024-03-03,2024-03-04,2024-03-06,2024-03-07,2024-03-09,1,Converted,1,1,1,1
3,U001003,2024-05-19,Organic,Mobile,East,45-54,Post-Intervention,2024-05,2024-05-19,2024-05-19,2024-05-22,NaN,NaN,NaN,0,Stage3,1,1,0,0
4,U001004,2024-04-18,Organic,Desktop,North,18-24,Post-Intervention,2024-04,2024-04-18,NaN,NaN,NaN,NaN,NaN,0,Stage1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,U012995,2024-02-22,Organic,Desktop,West,35-44,Pre-Intervention,2024-02,2024-02-22,2024-02-24,2024-02-26,2024-02-27,NaN,NaN,0,Stage4,1,1,1,0
11996,U012996,2024-06-08,Organic,Mobile,North,35-44,Post-Intervention,2024-06,2024-06-08,2024-06-10,2024-06-13,2024-06-15,2024-06-18,2024-06-18,1,Converted,1,1,1,1
11997,U012997,2024-04-25,Referral,Mobile,North,35-44,Post-Intervention,2024-04,2024-04-25,NaN,NaN,NaN,NaN,NaN,0,Stage1,0,0,0,0
11998,U012998,2024-01-01,Referral,Desktop,East,18-24,Pre-Intervention,2024-01,2024-01-01,NaN,NaN,NaN,NaN,NaN,0,Stage1,0,0,0,0
11999,U012999,2024-05-09,Organic,Desktop,Central,25-34,Post-Intervention,2024-05,2024-05-09,2024-05-11,2024-05-13,NaN,NaN,NaN,0,Stage3,1,1,0,0

In [4]:
df.drop(columns=['converted', 'exit_stage', 'reached_stage2', 'reached_stage3', 'reached_stage4', 'reached_stage5'], inplace=True)
df

,user_id,entry_date,segment,device,region,age_group,period,month,stage1_date,stage2_date,stage3_date,stage4_date,stage5_date,conversion_date
0,U001000,2024-06-12,Paid_Search,Tablet,West,35-44,Post-Intervention,2024-06,2024-06-12,2024-06-12,2024-06-13,2024-06-15,NaN,NaN
1,U001001,2024-03-11,Referral,Desktop,North,55+,Pre-Intervention,2024-03,2024-03-11,NaN,NaN,NaN,NaN,NaN
2,U001002,2024-03-03,Organic,Mobile,North,25-34,Pre-Intervention,2024-03,2024-03-03,2024-03-03,2024-03-04,2024-03-06,2024-03-07,2024-03-09
3,U001003,2024-05-19,Organic,Mobile,East,45-54,Post-Intervention,2024-05,2024-05-19,2024-05-19,2024-05-22,NaN,NaN,NaN
4,U001004,2024-04-18,Organic,Desktop,North,18-24,Post-Intervention,2024-04,2024-04-18,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,U012995,2024-02-22,Organic,Desktop,West,35-44,Pre-Intervention,2024-02,2024-02-22,2024-02-24,2024-02-26,2024-02-27,NaN,NaN
11996,U012996,2024-06-08,Organic,Mobile,North,35-44,Post-Intervention,2024-06,2024-06-08,2024-06-10,2024-06-13,2024-06-15,2024-06-18,2024-06-18
11997,U012997,2024-04-25,Referral,Mobile,North,35-44,Post-Intervention,2024-04,2024-04-25,NaN,NaN,NaN,NaN,NaN
11998,U012998,2024-01-01,Referral,Desktop,East,18-24,Pre-Intervention,2024-01,2024-01-01,NaN,NaN,NaN,NaN,NaN
11999,U012999,2024-05-09,Organic,Desktop,Central,25-34,Post-Intervention,2024-05,2024-05-09,2024-05-11,2024-05-13,NaN,NaN,NaN

In [5]:
#Converted Customers

df['converted'] = df['conversion_date'].notna().astype(int)
df

,user_id,entry_date,segment,device,region,age_group,period,month,stage1_date,stage2_date,stage3_date,stage4_date,stage5_date,conversion_date,converted
0,U001000,2024-06-12,Paid_Search,Tablet,West,35-44,Post-Intervention,2024-06,2024-06-12,2024-06-12,2024-06-13,2024-06-15,NaN,NaN,0
1,U001001,2024-03-11,Referral,Desktop,North,55+,Pre-Intervention,2024-03,2024-03-11,NaN,NaN,NaN,NaN,NaN,0
2,U001002,2024-03-03,Organic,Mobile,North,25-34,Pre-Intervention,2024-03,2024-03-03,2024-03-03,2024-03-04,2024-03-06,2024-03-07,2024-03-09,1
3,U001003,2024-05-19,Organic,Mobile,East,45-54,Post-Intervention,2024-05,2024-05-19,2024-05-19,2024-05-22,NaN,NaN,NaN,0
4,U001004,2024-04-18,Organic,Desktop,North,18-24,Post-Intervention,2024-04,2024-04-18,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,U012995,2024-02-22,Organic,Desktop,West,35-44,Pre-Intervention,2024-02,2024-02-22,2024-02-24,2024-02-26,2024-02-27,NaN,NaN,0
11996,U012996,2024-06-08,Organic,Mobile,North,35-44,Post-Intervention,2024-06,2024-06-08,2024-06-10,2024-06-13,2024-06-15,2024-06-18,2024-06-18,1
11997,U012997,2024-04-25,Referral,Mobile,North,35-44,Post-Intervention,2024-04,2024-04-25,NaN,NaN,NaN,NaN,NaN,0
11998,U012998,2024-01-01,Referral,Desktop,East,18-24,Pre-Intervention,2024-01,2024-01-01,NaN,NaN,NaN,NaN,NaN,0
11999,U012999,2024-05-09,Organic,Desktop,Central,25-34,Post-Intervention,2024-05,2024-05-09,2024-05-11,2024-05-13,NaN,NaN,NaN,0

In [6]:
#Exit Stage

import numpy as np
exit = [
    df['stage2_date'].isna(),
    df['stage3_date'].isna(),
    df['stage4_date'].isna(),
    df['stage5_date'].isna(),
    df['conversion_date'].isna()
]
choices = [
    'stage1',
    'stage2',
    'stage3',
    'stage4',
    'stage5'
]
df['exit_stage'] = np.select(exit, choices, default='Converted')
df

,user_id,entry_date,segment,device,region,age_group,period,month,stage1_date,stage2_date,stage3_date,stage4_date,stage5_date,conversion_date,converted,exit_stage
0,U001000,2024-06-12,Paid_Search,Tablet,West,35-44,Post-Intervention,2024-06,2024-06-12,2024-06-12,2024-06-13,2024-06-15,NaN,NaN,0,stage4
1,U001001,2024-03-11,Referral,Desktop,North,55+,Pre-Intervention,2024-03,2024-03-11,NaN,NaN,NaN,NaN,NaN,0,stage1
2,U001002,2024-03-03,Organic,Mobile,North,25-34,Pre-Intervention,2024-03,2024-03-03,2024-03-03,2024-03-04,2024-03-06,2024-03-07,2024-03-09,1,Converted
3,U001003,2024-05-19,Organic,Mobile,East,45-54,Post-Intervention,2024-05,2024-05-19,2024-05-19,2024-05-22,NaN,NaN,NaN,0,stage3
4,U001004,2024-04-18,Organic,Desktop,North,18-24,Post-Intervention,2024-04,2024-04-18,NaN,NaN,NaN,NaN,NaN,0,stage1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,U012995,2024-02-22,Organic,Desktop,West,35-44,Pre-Intervention,2024-02,2024-02-22,2024-02-24,2024-02-26,2024-02-27,NaN,NaN,0,stage4
11996,U012996,2024-06-08,Organic,Mobile,North,35-44,Post-Intervention,2024-06,2024-06-08,2024-06-10,2024-06-13,2024-06-15,2024-06-18,2024-06-18,1,Converted
11997,U012997,2024-04-25,Referral,Mobile,North,35-44,Post-Intervention,2024-04,2024-04-25,NaN,NaN,NaN,NaN,NaN,0,stage1
11998,U012998,2024-01-01,Referral,Desktop,East,18-24,Pre-Intervention,2024-01,2024-01-01,NaN,NaN,NaN,NaN,NaN,0,stage1
11999,U012999,2024-05-09,Organic,Desktop,Central,25-34,Post-Intervention,2024-05,2024-05-09,2024-05-11,2024-05-13,NaN,NaN,NaN,0,stage3

In [7]:
#Stage Progression
df['stage2_reached'] = df['stage2_date'].notna().astype(int)
df['stage3_reached'] = df['stage3_date'].notna().astype(int)
df['stage4_reached'] = df['stage4_date'].notna().astype(int)
df['stage5_reached'] = df['stage5_date'].notna().astype(int)
df

,user_id,entry_date,segment,device,region,age_group,period,month,stage1_date,stage2_date,stage3_date,stage4_date,stage5_date,conversion_date,converted,exit_stage,stage2_reached,stage3_reached,stage4_reached,stage5_reached
0,U001000,2024-06-12,Paid_Search,Tablet,West,35-44,Post-Intervention,2024-06,2024-06-12,2024-06-12,2024-06-13,2024-06-15,NaN,NaN,0,stage4,1,1,1,0
1,U001001,2024-03-11,Referral,Desktop,North,55+,Pre-Intervention,2024-03,2024-03-11,NaN,NaN,NaN,NaN,NaN,0,stage1,0,0,0,0
2,U001002,2024-03-03,Organic,Mobile,North,25-34,Pre-Intervention,2024-03,2024-03-03,2024-03-03,2024-03-04,2024-03-06,2024-03-07,2024-03-09,1,Converted,1,1,1,1
3,U001003,2024-05-19,Organic,Mobile,East,45-54,Post-Intervention,2024-05,2024-05-19,2024-05-19,2024-05-22,NaN,NaN,NaN,0,stage3,1,1,0,0
4,U001004,2024-04-18,Organic,Desktop,North,18-24,Post-Intervention,2024-04,2024-04-18,NaN,NaN,NaN,NaN,NaN,0,stage1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,U012995,2024-02-22,Organic,Desktop,West,35-44,Pre-Intervention,2024-02,2024-02-22,2024-02-24,2024-02-26,2024-02-27,NaN,NaN,0,stage4,1,1,1,0
11996,U012996,2024-06-08,Organic,Mobile,North,35-44,Post-Intervention,2024-06,2024-06-08,2024-06-10,2024-06-13,2024-06-15,2024-06-18,2024-06-18,1,Converted,1,1,1,1
11997,U012997,2024-04-25,Referral,Mobile,North,35-44,Post-Intervention,2024-04,2024-04-25,NaN,NaN,NaN,NaN,NaN,0,stage1,0,0,0,0
11998,U012998,2024-01-01,Referral,Desktop,East,18-24,Pre-Intervention,2024-01,2024-01-01,NaN,NaN,NaN,NaN,NaN,0,stage1,0,0,0,0
11999,U012999,2024-05-09,Organic,Desktop,Central,25-34,Post-Intervention,2024-05,2024-05-09,2024-05-11,2024-05-13,NaN,NaN,NaN,0,stage3,1,1,0,0

In [12]:
df_pre = df[df['period']=='Pre-Intervention'].copy()
df_pre = df_pre.drop(columns='period')
df_pre

,user_id,entry_date,segment,device,region,age_group,month,stage1_date,stage2_date,stage3_date,stage4_date,stage5_date,conversion_date,converted,exit_stage,stage2_reached,stage3_reached,stage4_reached,stage5_reached
1,U001001,2024-03-11,Referral,Desktop,North,55+,2024-03,2024-03-11,NaN,NaN,NaN,NaN,NaN,0,stage1,0,0,0,0
2,U001002,2024-03-03,Organic,Mobile,North,25-34,2024-03,2024-03-03,2024-03-03,2024-03-04,2024-03-06,2024-03-07,2024-03-09,1,Converted,1,1,1,1
5,U001005,2024-01-09,Email,Desktop,South,18-24,2024-01,2024-01-09,2024-01-09,2024-01-10,2024-01-10,2024-01-12,2024-01-14,1,Converted,1,1,1,1
8,U001008,2024-02-20,Referral,Desktop,North,18-24,2024-02,2024-02-20,2024-02-22,2024-02-25,2024-02-27,2024-03-02,2024-03-02,1,Converted,1,1,1,1
11,U001011,2024-01-02,Referral,Desktop,West,18-24,2024-01,2024-01-02,2024-01-02,2024-01-05,NaN,NaN,NaN,0,stage3,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11989,U012989,2024-01-16,Social,Desktop,North,35-44,2024-01,2024-01-16,NaN,NaN,NaN,NaN,NaN,0,stage1,0,0,0,0
11990,U012990,2024-02-02,Organic,Desktop,West,55+,2024-02,2024-02-02,2024-02-03,NaN,NaN,NaN,NaN,0,stage2,1,0,0,0
11994,U012994,2024-03-25,Organic,Desktop,East,35-44,2024-03,2024-03-25,2024-03-25,2024-03-27,2024-03-27,2024-03-30,2024-03-31,1,Converted,1,1,1,1
11995,U012995,2024-02-22,Organic,Desktop,West,35-44,2024-02,2024-02-22,2024-02-24,2024-02-26,2024-02-27,NaN,NaN,0,stage4,1,1,1,0
11998,U012998,2024-01-01,Referral,Desktop,East,18-24,2024-01,2024-01-01,NaN,NaN,NaN,NaN,NaN,0,stage1,0,0,0,0

In [16]:
df_post = df[df['period']=='Post-Intervention'].copy()
df_post = df_post.drop(columns='period')
df_post

,user_id,entry_date,segment,device,region,age_group,month,stage1_date,stage2_date,stage3_date,stage4_date,stage5_date,conversion_date,converted,exit_stage,stage2_reached,stage3_reached,stage4_reached,stage5_reached
0,U001000,2024-06-12,Paid_Search,Tablet,West,35-44,2024-06,2024-06-12,2024-06-12,2024-06-13,2024-06-15,NaN,NaN,0,stage4,1,1,1,0
3,U001003,2024-05-19,Organic,Mobile,East,45-54,2024-05,2024-05-19,2024-05-19,2024-05-22,NaN,NaN,NaN,0,stage3,1,1,0,0
4,U001004,2024-04-18,Organic,Desktop,North,18-24,2024-04,2024-04-18,NaN,NaN,NaN,NaN,NaN,0,stage1,0,0,0,0
6,U001006,2024-06-03,Email,Mobile,West,25-34,2024-06,2024-06-03,2024-06-03,NaN,NaN,NaN,NaN,0,stage2,1,0,0,0
7,U001007,2024-05-23,Organic,Tablet,West,55+,2024-05,2024-05-23,NaN,NaN,NaN,NaN,NaN,0,stage1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11992,U012992,2024-04-25,Organic,Tablet,South,45-54,2024-04,2024-04-25,2024-04-26,NaN,NaN,NaN,NaN,0,stage2,1,0,0,0
11993,U012993,2024-06-14,Paid_Search,Desktop,South,25-34,2024-06,2024-06-14,NaN,NaN,NaN,NaN,NaN,0,stage1,0,0,0,0
11996,U012996,2024-06-08,Organic,Mobile,North,35-44,2024-06,2024-06-08,2024-06-10,2024-06-13,2024-06-15,2024-06-18,2024-06-18,1,Converted,1,1,1,1
11997,U012997,2024-04-25,Referral,Mobile,North,35-44,2024-04,2024-04-25,NaN,NaN,NaN,NaN,NaN,0,stage1,0,0,0,0
11999,U012999,2024-05-09,Organic,Desktop,Central,25-34,2024-05,2024-05-09,2024-05-11,2024-05-13,NaN,NaN,NaN,0,stage3,1,1,0,0

In [15]:
df_pre.to_csv('first_transformations.csv', index=False)

In [17]:
df_post.to_csv('sec_transformations.csv', index=False)